### ISSUE TITLE
Create message types for hardware base protocol

### ISSUE THREAD

**Issue by elagil** [elagil/sigmadsp#16]
Replace string-based messages by types, like in
https://github.com/elagil/sigmadsp/blob/main/sigmadsp/communication/sigma_tcp_server.py#L23

_Originally posted by @elagil in https://github.com/elagil/sigmadsp/pull/13#discussion_r877481085_

**Comment by m0n5t3r** [comment]
I can do it after the current PRs get merged

**Comment by elagil** [comment]
Solved in latest PR
